### ISSUE TITLE
Opening tabbed tabs to the side

### ISSUE THREAD

**Issue by thallosaurus** [sayanarijit/preview-tabbed.xplr#1]
Hello, I'm currently writing a port of this plugin which does not need nnn and I'm wondering how I can open tabbed like you did on the preview gif?

Thanks in advance

**Comment by sayanarijit** [comment]
Hi... You can take a look at what [this plugin](https://github.com/jarun/nnn/blob/master/plugins/preview-tabbed) does... Specifically the `start_tabbed` function.

**Comment by thallosaurus** [comment]
I have read that function several times now, but I think I worded my question a bit wrong

On the attached screenshot you can see how it currently looks:
![2022-04-01-123403_1366x768_scrot](https://user-images.githubusercontent.com/12617951/161247250-17933577-aa54-4fb4-bfd4-2471e9e1acb6.png)

But I want the whole tabbed process to look like in your README.md gif, like no Tabs but rather each embedded client side by side. But how did you do that? I can't seem to figure out how

**Comment by sayanarijit** [comment]
Ah ok got your question now. Actually I use a tilling window manager (kwin), so it's automatic.

**Comment by sayanarijit** [comment]
Hope this answers your question. Closing this.
